set(MODULE_NEED_INSTALL TRUE)
set(MODULE_INSTALL_DIR "LibZip")

set(MODULE_CONFIG_ARGS
	-DBUILD_TOOLS=OFF -DBUILD_REGRESS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_DOC=OFF
	-DBUILD_SHARED_LIBS=OFF -DSHARED_LIB_VERSIONNING=OFF
	-DCMAKE_DEBUG_POSTFIX=_d -DCMAKE_RELWITHDEBINFO_POSTFIX=_rdi -DCMAKE_MINSIZEREL_POSTFIX=_ms
	-DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
	-DP3D_ROOT_PATH=${P3D_ROOT_PATH}
)