set(MODULE_NEED_INSTALL TRUE)
set(MODULE_INSTALL_DIR "Volk")

set(MODULE_CONFIG_ARGS
	-DVOLK_INSTALL=ON
	-DVOLK_STATIC_DEFINES=ON
)

if (WIN32)
	set(${MODULE_CONFIG_ARGS} -DVK_USE_PLATFORM_WIN32_KHR=ON)
endif()