set(MODULE_NEED_INSTALL TRUE)
set(MODULE_INSTALL_DIR "Volk")

set(MODULE_CONFIG_ARGS
	-DVOLK_INSTALL=ON
)

if ((${CMAKE_GENERATOR_PLATFORM} MATCHES Win32) OR (${CMAKE_GENERATOR_PLATFORM} MATCHES x64))
	set(MODULE_CONFIG_ARGS ${MODULE_CONFIG_ARGS} -DVOLK_STATIC_DEFINES=VK_USE_PLATFORM_WIN32_KHR)
endif()