#pragma once

#define VT_LAUNCHER_SUCCESS 0
#define VT_LAUNCHER_ENGINE_INIT_ERROR 1

#define VT_LAUNCHER_WINDOW_CREATION_ERROR 20
#define VT_LAUNCHER_WINDOW_PRESENTER_INIT_ERROR 21
#define VT_LAUNCHER_IMGUI_WINDOW_BACKEND_INIT_ERROR 30

#define VT_LAUNCHER_GAME_ARGS_ERROR 100
#define VT_LAUNCHER_GAME_INIT_ERROR 101

#define VT_LAUNCHER_RENDER_INIT_ERROR 500