#include "ManagedResourceHandles.h"

#include "ManagedResourceHandleReleaseDeclaration.h"

namespace VT
{
	MANAGED_GRAPHIC_RESOURCE_DESTROY_RELEASE_IMPL(GPUBufferResourceHandle, deleteGPUBufferInternal, deleteGPUBufferReference)

	MANAGED_GRAPHIC_RESOURCE_DESTROY_RELEASE_IMPL(Texture2DResourceHandle, deleteTexture2DInternal, deleteTexture2DReference)
	MANAGED_GRAPHIC_RESOURCE_VIEW_DESTROY_RELEASE_IMPL(Texture2DViewResourceHandle, deleteTexture2DViewInternal, deleteTexture2DViewReference)

	MANAGED_GRAPHIC_RESOURCE_DESTROY_RELEASE_IMPL(VertexShaderResourceHandle, deleteVertexShaderInternal, deleteVertexShaderReference)
	MANAGED_GRAPHIC_RESOURCE_DESTROY_RELEASE_IMPL(PixelShaderResourceHandle, deletePixelShaderInternal, deletePixelShaderReference)

	MANAGED_GRAPHIC_RESOURCE_RELEASE_IMPL(PipelineStateResourceHandle, deletePipelineStateInternal)

	NAMED_MANAGED_GRAPHIC_RESOURCE_DESTROY_IMPL(VertexShaderResourceHandle, deleteVertexShaderReference)
	NAMED_MANAGED_GRAPHIC_RESOURCE_DESTROY_IMPL(PixelShaderResourceHandle, deletePixelShaderReference)
}