#pragma once

#include "D3D12GraphicsPlugin/D3D12Core.h"
#include "Textures/TextureCommon.h"

namespace VT_D3D12
{
	inline D3D12_RESOURCE_STATES convertBufferStateVTtoD3D12(VT::GraphicResourceStateValueType state)
	{
		switch (state)
		{
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_SHADER_RESOURCE:
			return D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_SHADER_RESOURCE_COMPUTE:
			return D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_UNORDERED_ACCESS:
			return D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_COMMON_READ:
			return D3D12_RESOURCE_STATE_GENERIC_READ;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_COPY_SRC:
			return D3D12_RESOURCE_STATE_COPY_SOURCE;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_COPY_DEST:
			return D3D12_RESOURCE_STATE_COPY_DEST;

		case VT::GPUBufferState::GPU_BUFFER_STATE_VERTEX_BUFFER:
		case VT::GPUBufferState::GPU_BUFFER_STATE_CONSTANT_BUFFER:
			return D3D12_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER;
		case VT::GPUBufferState::GPU_BUFFER_STATE_INDEX_BUFFER:
			return D3D12_RESOURCE_STATE_INDEX_BUFFER;
		case VT::GPUBufferState::GPU_BUFFER_STATE_INDIRECT_ARGUMENT:
			return D3D12_RESOURCE_STATE_INDIRECT_ARGUMENT;

		case VT::CommonGraphicResourceState::GRAPHIC_STATE_UNDEFINED:
		default:
			return D3D12_RESOURCE_STATE_COMMON;
		}
	}


	inline D3D12_RESOURCE_STATES convertTextureStateVTtoD3D12(VT::GraphicResourceStateValueType state)
	{
		switch (state)
		{
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_SHADER_RESOURCE:
			return D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_SHADER_RESOURCE_COMPUTE:
			return D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_UNORDERED_ACCESS:
			return D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_COMMON_READ:
			return D3D12_RESOURCE_STATE_GENERIC_READ;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_COPY_SRC:
			return D3D12_RESOURCE_STATE_COPY_SOURCE;
		case VT::CommonGraphicResourceState::GRAPHIC_STATE_COPY_DEST:
			return D3D12_RESOURCE_STATE_COPY_DEST;

		case VT::TextureState::TEXTURE_STATE_RENDER_TARGET:
			return D3D12_RESOURCE_STATE_RENDER_TARGET;
		case VT::TextureState::TEXTURE_STATE_DEPTH_STENCIL:
			return D3D12_RESOURCE_STATE_DEPTH_WRITE;
		case VT::TextureState::TEXTURE_STATE_DEPTH_STENCIL_READONLY:
			return D3D12_RESOURCE_STATE_DEPTH_READ;
		case VT::TextureState::TEXTURE_STATE_PRESENTING:
			return D3D12_RESOURCE_STATE_PRESENT;

		case VT::CommonGraphicResourceState::GRAPHIC_STATE_UNDEFINED:
		default:
			return D3D12_RESOURCE_STATE_COMMON;
		}
	}
}
