if (NOT DEFINED VT_MESSAGE_COLORS)
	string(ASCII 27 Esc)
	set(VT_COLOUR_RESET			"${Esc}[m")
	set(VT_COLOUR_BOLD			"${Esc}[1m")
	set(VT_COLOUR_RED			"${Esc}[31m")
	set(VT_COLOUR_GREEN			"${Esc}[32m")
	set(VT_COLOUR_YELLOW		"${Esc}[33m")
	set(VT_COLOUR_BLUE 			"${Esc}[34m")
	set(VT_COLOUR_MAGENTA		"${Esc}[35m")
	set(VT_COLOUR_CYAN			"${Esc}[36m")
	set(VT_COLOUR_WHITE			"${Esc}[37m")
	set(VT_COLOUR_BOLD_RED		"${Esc}[1;31m")
	set(VT_COLOUR_BOLD_GREEN	"${Esc}[1;32m")
	set(VT_COLOUR_BOLD_YELLOW	"${Esc}[1;33m")
	set(VT_COLOUR_BOLD_BLUE 	"${Esc}[1;34m")
	set(VT_COLOUR_BOLD_MAGENTA	"${Esc}[1;35m")
	set(VT_COLOUR_BOLD_CYAN		"${Esc}[1;36m")
	set(VT_COLOUR_BOLD_WHITE	"${Esc}[1;37m")
	
	set(VT_MESSAGE_COLORS)
endif()