if(NOT DEFINED VT_CONFIGURATIONS)
	set(VT_CONFIGURATIONS)

	set(VT_CONFIGURATION_TYPES Debug Release Profile Retail)

	set(CMAKE_C_FLAGS_RETAIL ${CMAKE_C_FLAGS_RELEASE})
	set(CMAKE_CXX_FLAGS_RETAIL ${CMAKE_CXX_FLAGS_RELEASE})
	set(CMAKE_EXE_LINKER_FLAGS_RETAIL ${CMAKE_EXE_LINKER_FLAGS_RELEASE})
	set(CMAKE_SHARED_LINKER_FLAGS_RETAIL ${CMAKE_SHARED_LINKER_FLAGS_RELEASE})

	set(CMAKE_C_FLAGS_PROFILE ${CMAKE_C_FLAGS_RELWITHDEBINFO})
	set(CMAKE_CXX_FLAGS_PROFILE ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})
	set(CMAKE_EXE_LINKER_FLAGS_PROFILE ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO})
	set(CMAKE_SHARED_LINKER_FLAGS_PROFILE ${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO})

	set(CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELWITHDEBINFO})
	set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELWITHDEBINFO})
	set(CMAKE_EXE_LINKER_FLAGS_RELEASE ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO})
	set(CMAKE_SHARED_LINKER_FLAGS_RELEASE ${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO})

	add_compile_definitions(
		VT_CONFIG=$<CONFIG>
		VT_CONFIG_NAME="$<CONFIG>"

		$<$<CONFIG:Debug>:VT_CONFIG_DEBUG>
		$<$<CONFIG:Release>:VT_CONFIG_RELEASE>
		$<$<CONFIG:Profile>:VT_CONFIG_PROFILE>
		$<$<CONFIG:Retail>:VT_CONFIG_RETAIL>
	)

	set(CMAKE_CONFIGURATION_TYPES ${VT_CONFIGURATION_TYPES})
endif()