if(NOT DEFINED WIN_SDK_OPTION_SET)
	if("$ENV{WIN10_SDK_PATH}$ENV{WIN10_SDK_VERSION}" STREQUAL "")
		get_filename_component(WIN10_SDK_PATH "[HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows Kits\\Installed Roots;KitsRoot10]" ABSOLUTE CACHE)
		set(WIN10_SDK_VERSION ${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION})
	elseif()
		set(WIN10_SDK_PATH $ENV{WIN10_SDK_PATH})
		set(WIN10_SDK_VERSION $ENV{WIN10_SDK_VERSION})
	endif()

	set(WIN_SDK_OPTION_SET)

	set(WIN_SDK_PATH ${WIN10_SDK_PATH})
	set(WIN_SDK_VERSION ${WIN10_SDK_VERSION})
endif()